### ISSUE TITLE
Serializable interface is deprecated

### ISSUE THREAD

**Issue by tricsusz** [el-abdel/ABELkeycloakBearerOnlyAdapterBundle#10]
I get the following deprecated message:
``
Deprecated: ABEL\Bundle\keycloakBearerOnlyAdapterBundle\Security\User\KeycloakBearerUser implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/symfony/vendor/abel/keycloak-bearer-only-adapter-bundle/Security/User/KeycloakBearerUser.php on line 9
``

@el-abdel can you pls fix it?

**Comment by el-abdel** [comment]
hello, @tricsusz,

Thanks for reporting this issue, I will merge your PR and tag a new version 1.3.2

I'll let you tell me if it's ok for you ;)

**Comment by tricsusz** [comment]
> hello, @tricsusz,
> 
> Thanks for reporting this issue, I will merge your PR and tag a new version 1.3.2
> 
> I'll let you tell me if it's ok for you ;)

Perfect, thank you :)
