### ISSUE TITLE
Installation failled with symfony 5.4

### ISSUE THREAD

**Issue by michee1367** [el-abdel/ABELkeycloakBearerOnlyAdapterBundle#4]
User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::getContainerExtension()" might add "?ExtensionInterface" as a native return type declaration in the future. Do the same in child class "ABEL\Bundle\keycloakBearerOnlyAdapterBundle\ABELkeycloakBearerOnlyAdapterBundle" now to avoid errors or add an explicit @return annotation to suppress this message

**Comment by el-abdel** [comment]
Hi,

Which version of the bundle you're using ?

**Comment by michee1367** [comment]
Thank Mr.
I use the >=v1.2.0 of the bundle

**Comment by el-abdel** [comment]
Ok i'll fix that, thanks for reporting the issue 🙏
