### ISSUE TITLE
Newer version of keycloak doesn't have '/auth' in the URL

### ISSUE THREAD

**Issue by tricsusz** [el-abdel/ABELkeycloakBearerOnlyAdapterBundle#7]
It should be removed from KeycloakBearerUserProvider.

Am I wrong?

My Keycloak version is 17.0.0.

**Comment by el-abdel** [comment]
Hi @tricsusz,

Thanks for reporting this issue, I'll check it out.

**Comment by tricsusz** [comment]
Hi @el-abdel ,

Could you please remove the '/auth' part from v1.2 too? My Symfony version is 5.4, therefore I can't update to 1.3.

**Comment by el-abdel** [comment]
Yes, sure i'll take care of that.

**Comment by el-abdel** [comment]
> Hi @el-abdel ,
> 
> Could you please remove the '/auth' part from v1.2 too? My Symfony version is 5.4, therefore I can't update to 1.3.

Hi, Version v1.2.2 support keycloak changes, you can use it.

**Comment by tricsusz** [comment]
> > Hi @el-abdel ,
> > Could you please remove the '/auth' part from v1.2 too? My Symfony version is 5.4, therefore I can't update to 1.3.
> 
> Hi, Version v1.2.2 support keycloak changes, you can use it.

Thank you @el-abdel !
